query availablePlugins {
  plugins {
    nodes {
      id
      name
      description
      creator {
        name
      }
      averageRating
      versions(last: 1) {
        nodes {
          version {
            major
            minor
            patch
          }
          uri
        }
      }
    }
  }
}

query installedPlugins($id: Int!) {
  plugins(where: { id: { eq: $id } }) {
    nodes {
      name
      description
      creator {
        name
      }
      averageRating
    }
  }
}

query myPluginsList($id: Int!)  {
  plugins(where: { creator: { id: { eq: $id } } }) {
    nodes {
      id
      name
    }
  }
}

query myPluginsInfo($id: Int!)  {
  plugins(where: { id: { eq: $id } }) {
    nodes {
      name
      description
      averageRating
      versions {
        nodes {
          version {
            major
            minor
            patch
          }
          uri
        }
      }
    }
  }
}
